[package]
name = "vilbat/composition"
version = "0.1.7"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@1.1.0"
Trove = "sleitnick/trove@0.4.0"
Promise = "evaera/promise@4.0.0"
Symbol = "sleitnick/symbol@2.0.0"
TableUtil = "sleitnick/table-util@1.1.1"